Universe 	= vanilla
Executable 	= myscript.csh
notification 	= Never
Output  	= condor.out
Error         = condor.err
Log  		= /dev/null
# in case your script is in another directory, set initialdir to it
#Initialdir  	= 
# Jobs by default are allowed 1.8Gb of RAM, you need to ask for more if needed
# with request_memory, per 2GB memory it allocates another condor slot (and
# charges your priority for it)
#  request_memory = 4.1GB
Queue
